import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import styles from "./Home.module.css";

import { api } from "~/utils/api";

export default function Home() {
  
  

  return (
    <>
      <Head>
        <title>MineTrax</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex min-h-screen flex-col items-center justify-center ${styles["bg-image"]}`}>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-centered ">
        <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
          <span className="text-[hsl(120,100%,70%)]">Mine</span>
          <span className="text-[hsl(50,100%,0%)]">Trax</span>
        </h1>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
              style={{ backgroundColor: "blue" }}
            >
              <h3 className="text-2xl font-bold text-[hsl(90,100%,40%)] "> Login →</h3>
              <div className="text-lg">
              (Login Info) 
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank" 
              style={{ backgroundColor: "blue" }}
            >
              <h3 className="text-2xl font-bold text-[hsl(90,100%,40%)]">Sign Up →</h3>
              <div className="text-lg">
                (Sign Up Info)
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-[hsl(120,100%,50%)]">
              Begin Tracking...
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main> 
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-black ">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
